"""add embedding cache table

Revision ID: 285f39dc7f86
Revises: 9b4648f34603
Create Date: 2026-07-03 14:07:00.304253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '285f39dc7f86'
down_revision: Union[str, None] = '9b4648f34603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_cache_id'), 'embedding_cache', ['id'], unique=False)
    op.create_index(op.f('ix_embedding_cache_text_hash'), 'embedding_cache', ['text_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_cache_text_hash'), table_name='embedding_cache')
    op.drop_index(op.f('ix_embedding_cache_id'), table_name='embedding_cache')
    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
