"""add embedding column to expenses schedules todos

Revision ID: 3b2773b8cefb
Revises: 285f39dc7f86
Create Date: 2026-07-14 15:35:52.909843

"""
import pgvector.sqlalchemy
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2773b8cefb'
down_revision: Union[str, None] = '285f39dc7f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('schedules', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('todos', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'embedding')
    op.drop_column('schedules', 'embedding')
    op.drop_column('expenses', 'embedding')
    # ### end Alembic commands ###
